import React from 'react';
import {version} from '../../package.json';
import Board from './Board';

const BG = '#555555';
const BLUE = '#0066CC';
const SKY = '#3399CC';
const LIGHT_GRAY = '#d9edf7';
const WHITE = '#FFFFFF';
const HAIR = '#663300';
const SKIN = '#FFCC66';
const YELLOW = '#FFFF33';
const PINK = '#DA4F49';

const App = ({children}) => (
    <Board
        debug={true}
        w={10}
        h={10}
        seed={
            [
                [
                    {static: BG},
                    {static: BG},
                    {static: BG},
                    {static: BG},
                    {static: BG},
                    {before: BLUE, after: HAIR},
                    {before: BLUE, after: HAIR},
                    {before: BLUE, after: HAIR},
                    {before: BLUE, after: HAIR},
                    {before: BLUE, after: HAIR},
                    {static: BG},
                    {static: BG},
                    {static: BG},
                    {static: BG},
                    {static: BG},
                    {static: BG}
                ],
                [
                    {static: BG},
                    {static: BG},
                    {static: BG},
                    {static: BG},
                    {before: BLUE, after: HAIR},
                    {before: BLUE, after: HAIR},
                    {before: BLUE, after: HAIR},
                    {before: BLUE, after: HAIR},
                    {before: BLUE, after: HAIR},
                    {before: BLUE, after: HAIR},
                    {before: BLUE, after: HAIR},
                    {before: BLUE, after: BG},
                    {before: BLUE, after: BG},
                    {static: BG},
                    {static: BG},
                    {static: BG}
                ],
                [
                    {static: BG},
                    {static: BG},
                    {static: BG},
                    {static: BG},
                    {static: HAIR},
                    {static: HAIR},
                    {static: HAIR},
                    {static: SKIN},
                    {static: HAIR},
                    {static: SKIN},
                    {static: BG},
                    {static: BG},
                    {static: BG},
                    {static: BG},
                    {static: BG},
                    {static: BG}
                ],
                [
                    {static: BG},
                    {static: BG},
                    {static: BG},
                    {static: HAIR},
                    {static: SKIN},
                    {static: HAIR},
                    {static: SKIN},
                    {static: SKIN},
                    {static: HAIR},
                    {static: SKIN},
                    {static: SKIN},
                    {static: SKIN},
                    {static: BG},
                    {static: BG},
                    {static: BG},
                    {static: BG}
                ],
                [
                    {static: BG},
                    {static: BG},
                    {static: BG},
                    {static: HAIR},
                    {static: SKIN},
                    {static: HAIR},
                    {static: HAIR},
                    {static: SKIN},
                    {static: SKIN},
                    {before: HAIR, after: SKIN},
                    {static: SKIN},
                    {static: SKIN},
                    {static: SKIN},
                    {static: BG},
                    {static: BG},
                    {static: BG}
                ],
                [
                    {static: BG},
                    {static: BG},
                    {static: BG},
                    {static: HAIR},
                    {static: HAIR},
                    {static: SKIN},
                    {static: SKIN},
                    {static: SKIN},
                    {before: HAIR, after: SKIN},
                    {before: HAIR, after: PINK},
                    {before: HAIR, after: PINK},
                    {before: HAIR, after: SKIN},
                    {static: BG},
                    {static: BG},
                    {static: BG},
                    {static: BG}
                ],
                [
                    {static: BG},
                    {static: BG},
                    {static: BG},
                    {static: BG},
                    {static: BG},
                    {static: SKIN},
                    {static: SKIN},
                    {static: SKIN},
                    {static: SKIN},
                    {static: SKIN},
                    {static: SKIN},
                    {static: BG},
                    {static: BG},
                    {static: BG},
                    {static: BG},
                    {static: BG}
                ],
                [
                    {static: BG},
                    {static: BG},
                    {static: BG},
                    {before: SKY, after: SKIN},
                    {before: SKY, after: SKIN},
                    {before: SKY, after: SKIN},
                    {before: BLUE, after: SKIN},
                    {before: SKY, after: SKIN},
                    {before: SKY, after: SKIN},
                    {before: SKY, after: SKIN},
                    {static: BG},
                    {static: BG},
                    {static: BG},
                    {static: BG},
                    {static: BG},
                    {static: BG}
                ],
                [
                    {static: BG},
                    {static: BG},
                    {before: SKY, after: SKIN},
                    {before: SKY, after: SKIN},
                    {before: SKY, after: SKIN},
                    {before: SKY, after: SKIN},
                    {before: BLUE, after: SKIN},
                    {before: SKY, after: SKIN},
                    {before: SKY, after: SKIN},
                    {before: BLUE, after: SKIN},
                    {before: SKY, after: SKIN},
                    {before: SKY, after: SKIN},
                    {before: SKY, after: SKIN},
                    {static: BG},
                    {static: BG},
                    {static: BG}
                ],
                [
                    {static: BG},
                    {before: SKY, after: SKIN},
                    {before: SKY, after: SKIN},
                    {before: SKY, after: SKIN},
                    {before: SKY, after: SKIN},
                    {before: SKY, after: PINK},
                    {before: BLUE, after: SKIN},
                    {before: BLUE, after: SKIN},
                    {before: BLUE, after: SKIN},
                    {before: BLUE, after: SKIN},
                    {before: SKY, after: PINK},
                    {before: SKY, after: SKIN},
                    {before: SKY, after: SKIN},
                    {before: SKY, after: SKIN},
                    {static: BG},
                    {static: BG}
                ],
                [
                    {static: BG},
                    {before: LIGHT_GRAY, after: SKIN},
                    {before: WHITE, after: SKIN},
                    {before: WHITE, after: SKIN},
                    {before: SKY, after: SKIN},
                    {before: BLUE, after: SKIN},
                    {before: YELLOW, after: SKIN},
                    {before: BLUE, after: SKIN},
                    {before: BLUE, after: SKIN},
                    {before: YELLOW, after: SKIN},
                    {before: BLUE, after: SKIN},
                    {before: SKY, after: SKIN},
                    {before: WHITE, after: SKIN},
                    {before: WHITE, after: SKIN},
                    {before: WHITE, after: SKIN},
                    {static: BG}
                ],
                [
                    {static: BG},
                    {before: LIGHT_GRAY, after: SKIN},
                    {before: WHITE, after: SKIN},
                    {before: WHITE, after: SKIN},
                    {before: WHITE, after: SKIN},
                    {before: BLUE, after: SKIN},
                    {before: BLUE, after: SKIN},
                    {before: BLUE, after: SKIN},
                    {before: BLUE, after: SKIN},
                    {before: BLUE, after: SKIN},
                    {before: BLUE, after: SKIN},
                    {before: WHITE, after: SKIN},
                    {before: WHITE, after: SKIN},
                    {before: WHITE, after: SKIN},
                    {before: WHITE, after: SKIN},
                    {static: BG}
                ],
                [
                    {static: BG},
                    {before: LIGHT_GRAY, after: SKIN},
                    {before: WHITE, after: SKIN},
                    {before: WHITE, after: SKIN},
                    {before: BLUE, after: SKIN},
                    {before: BLUE, after: SKIN},
                    {before: BLUE, after: SKIN},
                    {before: BLUE, after: SKIN},
                    {before: BLUE, after: SKIN},
                    {before: BLUE, after: SKIN},
                    {before: BLUE, after: SKIN},
                    {before: BLUE, after: SKIN},
                    {before: WHITE, after: SKIN},
                    {before: WHITE, after: SKIN},
                    {before: WHITE, after: SKIN},
                    {static: BG}
                ],
                [
                    {static: BG},
                    {static: BG},
                    {static: BG},
                    {static: BG},
                    {before: BLUE, after: SKIN},
                    {before: BLUE, after: SKIN},
                    {before: BLUE, after: SKIN},
                    {static: BG},
                    {static: BG},
                    {before: BLUE, after: SKIN},
                    {before: BLUE, after: SKIN},
                    {before: BLUE, after: SKIN},
                    {static: BG},
                    {static: BG},
                    {static: BG},
                    {static: BG}
                ],
                [
                    {static: BG},
                    {static: BG},
                    {static: BG},
                    {before: SKY, after: SKIN},
                    {before: SKY, after: SKIN},
                    {before: SKY, after: SKIN},
                    {static: BG},
                    {static: BG},
                    {static: BG},
                    {static: BG},
                    {before: SKY, after: SKIN},
                    {before: SKY, after: SKIN},
                    {before: SKY, after: SKIN},
                    {static: BG},
                    {static: BG},
                    {static: BG}
                ],
                [
                    {static: BG},
                    {static: BG},
                    {before: BLUE, after: SKIN},
                    {before: BLUE, after: SKIN},
                    {before: BLUE, after: SKIN},
                    {before: BLUE, after: SKIN},
                    {static: BG},
                    {static: BG},
                    {static: BG},
                    {static: BG},
                    {before: BLUE, after: SKIN},
                    {before: BLUE, after: SKIN},
                    {before: BLUE, after: SKIN},
                    {before: BLUE, after: SKIN},
                    {static: BG},
                    {static: BG}
                ],
            ]
        }
    />
);

App.propTypes = {children: React.PropTypes.object};

export default App;
